"""Browser property spoofing — the JS object surface, derived from the profile.

v2.12 made HTTP headers coherent with the TLS target. That is only half the
story: the page can read `navigator.languages`, `Intl.DateTimeFormat().timeZone`,
`screen.width`, the unmasked WebGL renderer and a canvas hash, and compare all
of them against the headers it just received. Multi-layer web-agent
fingerprinting (arXiv:2606.30119) shows superficial stealth patches make an
agent *more* detectable when those layers disagree — so the fix is not "spoof
harder", it is "derive every value from the same identity".

Every value here comes from a :class:`~omk_crawl.fingerprint.FingerprintProfile`
plus an explicit seed. Two consequences worth stating:

  **Temporal stability.** Canvas and audio noise are generated by a seeded LCG
  embedded in the script, so the same ``(profile, seed)`` produces the *same*
  noise on every call. A machine that resamples its canvas hash on each visit is
  flagged by the over-time axis of FP-Inconsistent (arXiv:2406.07647); a machine
  that never changes is consistent with a real device.

  **Geometry sanity.** Screen dimensions are derived *from* the profile viewport
  rather than invented, so the invariant detectors actually check — screen must
  never be smaller than the viewport — holds by construction.

Not spoofed, and said plainly rather than faked: font enumeration, WebRTC
candidate surfaces, and TLS-level properties. Those need a browser build or
network layer, not an init script.
"""

from __future__ import annotations

import hashlib
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from omk_crawl.fingerprint import FingerprintProfile

__all__ = [
    "BOOTSTRAP",
    "BrowserPropertySpec",
    "UNSUPPORTED_SURFACES",
    "WebglIdentity",
    "audit_props",
    "probe_script",
    "property_spec",
    "props_body",
    "spoof_script",
    "webgl_identity",
]

# Said out loud (P1): these cannot be fixed from an init script.
UNSUPPORTED_SURFACES: dict[str, str] = {
    "fonts": "font enumeration needs a fontconfig-level change, not a JS patch",
    "webrtc": "ICE candidate IPs come from the network stack, not the page",
    "tls": "covered by tls.py + curl_cffi impersonation",
    "audio_context_offscreen": "OfflineAudioContext rendering differs subtly per engine build",
}

_PLATFORM_STRINGS: dict[str, str] = {
    "Windows": "Win32",
    "macOS": "MacIntel",
    "Linux": "Linux x86_64",
    "Android": "Linux armv81",
    "iOS": "iPhone",
    "Chrome OS": "Linux x86_64",
}

# Device pixel ratios real machines actually report, per OS class. macOS has
# one entry on purpose: every modern Mac drives a Retina panel at DPR 2, so a
# 1.0 here would contradict the platform rather than add variety. The coherence
# audit caught exactly that during development — a macOS plan with a 1680px
# viewport and DPR 1 was flagged, and the pool was wrong, not the audit.
_DPR_BY_OS: dict[str, tuple[float, ...]] = {
    "macOS": (2.0,),
    "Windows": (1.0, 1.25, 1.5, 1.0),
    "Linux": (1.0, 1.0, 1.25),
    "Android": (2.75, 3.0, 2.625),
    "iOS": (3.0, 2.0, 3.0),
}


@dataclass(frozen=True, slots=True)
class WebglIdentity:
    """WebGL vendor/renderer strings for a platform.

    Software renderers (SwiftShader, llvmpipe) betray a GPU-less headless host,
    so these always name real hardware for the claimed OS.
    """

    vendor: str
    renderer: str
    unmasked_vendor: str
    unmasked_renderer: str


# Real ANGLE/Apple/Mesa renderer strings, keyed by OS. Chosen so the renderer
# family is plausible for the platform the UA already claims.
_WEBGL_BY_OS: dict[str, tuple[WebglIdentity, ...]] = {
    "Windows": (
        WebglIdentity(
            "Google Inc. (NVIDIA)",
            "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)",
            "Google Inc. (NVIDIA)",
            "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)",
        ),
        WebglIdentity(
            "Google Inc. (Intel)",
            "ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)",
            "Google Inc. (Intel)",
            "ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)",
        ),
    ),
    "macOS": (
        WebglIdentity(
            "Google Inc. (Apple)",
            "ANGLE (Apple, ANGLE Metal Renderer: Apple M2, Unspecified Version)",
            "Google Inc. (Apple)",
            "ANGLE (Apple, ANGLE Metal Renderer: Apple M2, Unspecified Version)",
        ),
        WebglIdentity(
            "Google Inc. (Apple)",
            "ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Pro, Unspecified Version)",
            "Google Inc. (Apple)",
            "ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Pro, Unspecified Version)",
        ),
    ),
    "Linux": (
        WebglIdentity(
            "Google Inc. (AMD)",
            "ANGLE (AMD, AMD Radeon RX 6600 (radeonsi, navi23, LLVM 17.0.6, DRM 3.54), OpenGL 4.6)",
            "Google Inc. (AMD)",
            "ANGLE (AMD, AMD Radeon RX 6600 (radeonsi, navi23, LLVM 17.0.6, DRM 3.54), OpenGL 4.6)",
        ),
        WebglIdentity(
            "Google Inc. (Intel)",
            "ANGLE (Intel, Mesa Intel(R) UHD Graphics 620 (KBL GT2), OpenGL 4.6)",
            "Google Inc. (Intel)",
            "ANGLE (Intel, Mesa Intel(R) UHD Graphics 620 (KBL GT2), OpenGL 4.6)",
        ),
    ),
    "Android": (
        WebglIdentity(
            "Qualcomm",
            "Adreno (TM) 740",
            "Qualcomm",
            "Adreno (TM) 740",
        ),
    ),
    "iOS": (
        WebglIdentity(
            "Apple Inc.",
            "Apple GPU",
            "Apple Inc.",
            "Apple GPU",
        ),
    ),
}


def _seed_int(seed: int | str | bytes | None, profile_name: str) -> int:
    """Stable 64-bit seed (``None`` derives from the profile name)."""
    if seed is None:
        seed = profile_name
    if isinstance(seed, int):
        return seed & 0xFFFFFFFFFFFFFFFF
    if isinstance(seed, str):
        seed = seed.encode("utf-8")
    return int.from_bytes(hashlib.sha256(seed).digest()[:8], "big")


class _Rng:
    """Tiny deterministic PRNG — a fixed reference so Python and JS agree.

    Deliberately the same 32-bit LCG used by the emitted JavaScript, so the
    values chosen here are reproducible by the page without shipping a table.
    """

    def __init__(self, seed: int) -> None:
        self._state = seed & 0xFFFFFFFF

    def next(self) -> float:
        self._state = (self._state * 1664525 + 1013904223) & 0xFFFFFFFF
        return self._state / 0x100000000

    def pick(self, options: tuple[Any, ...]) -> Any:
        return options[int(self.next() * len(options)) % len(options)]

    def between(self, lo: float, hi: float) -> float:
        return lo + self.next() * (hi - lo)


def webgl_identity(profile: FingerprintProfile) -> WebglIdentity:
    """WebGL identity matching the profile's platform (deterministic)."""
    options = _WEBGL_BY_OS.get(profile.platform_os, _WEBGL_BY_OS["Linux"])
    return options[_seed_int(profile.name, profile.name) % len(options)]


@dataclass(frozen=True, slots=True)
class BrowserPropertySpec:
    """The full JS surface derived from one identity.

    Attributes:
        profile / seed: Inputs, kept so the spec is self-describing.
        platform: ``navigator.platform`` for the claimed OS.
        languages: ``navigator.languages`` — first entry is the profile locale.
        timezone: IANA zone from the profile.
        screen: ``(width, height)`` — always ≥ the profile viewport.
        avail: ``(width, height)`` minus taskbar/dock, still ≥ viewport.
        device_pixel_ratio: Plausible DPR for the OS class.
        hardware_concurrency / device_memory: Plausible mid-range values.
        max_touch_points: 0 on desktop identities, 5 on mobile ones.
        webgl: Renderer strings for the platform.
        canvas_noise / audio_noise: Seed of the deterministic perturbation
            applied to canvas/audio reads.
    """

    profile: str
    seed: int
    platform: str
    languages: tuple[str, ...]
    timezone: str
    screen: tuple[int, int]
    avail: tuple[int, int]
    device_pixel_ratio: float
    hardware_concurrency: int
    device_memory: int
    max_touch_points: int
    webgl: WebglIdentity
    canvas_noise: int
    audio_noise: int

    def to_dict(self) -> dict[str, Any]:
        """JSON-safe summary (no JS, safe for result metadata)."""
        return {
            "profile": self.profile,
            "platform": self.platform,
            "languages": list(self.languages),
            "timezone": self.timezone,
            "screen": list(self.screen),
            "avail": list(self.avail),
            "device_pixel_ratio": self.device_pixel_ratio,
            "hardware_concurrency": self.hardware_concurrency,
            "device_memory": self.device_memory,
            "max_touch_points": self.max_touch_points,
            "webgl_renderer": self.webgl.unmasked_renderer,
        }


def _languages_for(profile: FingerprintProfile) -> tuple[str, ...]:
    """Language list from ``Accept-Language`` so header and JS agree."""
    tags: list[str] = []
    for part in profile.accept_language.split(","):
        tag = part.split(";")[0].strip()
        if tag and tag not in tags:
            tags.append(tag)
    if profile.locale not in tags:
        tags.insert(0, profile.locale)
    return tuple(tags)


def property_spec(
    profile: FingerprintProfile,
    seed: int | str | bytes | None = None,
) -> BrowserPropertySpec:
    """Derive the full JS surface for ``profile`` (deterministic in ``seed``)."""
    seed_value = _seed_int(seed, profile.name)
    rng = _Rng(seed_value)

    viewport_w, viewport_h = profile.viewport
    # Browser chrome above the viewport, then a taskbar/dock away from the work
    # area. Both are bounded so `avail >= viewport` cannot fail.
    chrome_h = int(rng.between(96, 148))
    screen_h = viewport_h + chrome_h
    avail_h = max(viewport_h, screen_h - int(rng.between(32, 64)))

    dpr = rng.pick(_DPR_BY_OS.get(profile.platform_os, (1.0,)))
    # A macOS identity with a viewport too wide for a Retina panel would be a
    # contradiction; keep the panel ratio truthful regardless of what the pool
    # holds (defensive: the pool currently only offers 2.0).
    if profile.platform_os == "macOS" and dpr == 1.0 and viewport_w > 1600:
        dpr = 2.0

    mobile = profile.mobile or profile.platform_os in ("Android", "iOS")
    return BrowserPropertySpec(
        profile=profile.name,
        seed=seed_value,
        platform=_PLATFORM_STRINGS.get(profile.platform_os, "Linux x86_64"),
        languages=_languages_for(profile),
        timezone=profile.timezone_id,
        screen=(viewport_w, screen_h),
        avail=(viewport_w, avail_h),
        device_pixel_ratio=dpr,
        hardware_concurrency=int(rng.pick((4, 8, 8, 12, 16))),
        device_memory=int(rng.pick((8, 8, 16, 4))),
        max_touch_points=5 if mobile else 0,
        webgl=webgl_identity(profile),
        canvas_noise=(seed_value & 0x7FFFFFFF) or 1,
        audio_noise=((seed_value >> 13) & 0x7FFFFFFF) or 1,
    )


def _js_value(value: Any) -> str:
    """Render a Python value as a JS literal (JSON is a JS subset here)."""
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
        return f"'{escaped}'"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, (tuple, list)):
        return "[" + ", ".join(_js_value(v) for v in value) + "]"
    raise TypeError(f"cannot render {type(value).__name__} as JS")


_PLUGINS_JS = """
  const pdfMime = ['application/pdf', 'text/pdf'];
  const pdfDesc = 'Portable Document Format';
  const viewer = (name) => ({ name, filename: 'internal-pdf-viewer', desc: pdfDesc });
  const pluginEntries = [
    viewer('PDF Viewer'),
    viewer('Chrome PDF Viewer'),
    viewer('Chromium PDF Viewer'),
    viewer('Microsoft Edge PDF Viewer'),
    viewer('WebKit built-in PDF'),
  ];
  const makeMime = (type) => ({ type, suffixes: 'pdf', description: pdfDesc,
                                enabledPlugin: null });
  const pluginList = pluginEntries.map((p) => {
    const mimes = pdfMime.map(makeMime);
    const plugin = {
      name: p.name, filename: p.filename, description: p.desc, length: mimes.length,
    };
    mimes.forEach((m, i) => { Object.defineProperty(plugin, i, { value: m, enumerable: true }); });
    mimes.forEach((m) => Object.defineProperty(m, 'enabledPlugin', { value: plugin }));
    return plugin;
  });
  pluginList.item = native(function item(i) { return pluginList[i] || null; }, 'item', 1);
  pluginList.namedItem = native(function namedItem(n) {
    return pluginList.find((p) => p.name === n) || null;
  }, 'namedItem', 1);
  define(Navigator.prototype, 'plugins', pluginList);
  const mimeList = pluginList.flatMap((p) => pdfMime.map(makeMime));
  mimeList.item = native(function item(i) { return mimeList[i] || null; }, 'item', 1);
  mimeList.namedItem = native(function namedItem(n) {
    return mimeList.find((m) => m.type === n) || null;
  }, 'namedItem', 1);
  define(Navigator.prototype, 'mimeTypes', mimeList);
  define(Navigator.prototype, 'pdfViewerEnabled', true);
""".strip("\n")

# Deterministic LCG: identical to browser_props._Rng, so the page reproduces
# the same stream the planner used without shipping a lookup table.
_NOISE_JS = """
  const makeNoise = (seed) => {
    let s = seed >>> 0;
    return () => { s = (Math.imul(s, 1664525) + 1013904223) >>> 0; return s / 4294967296; };
  };
""".strip("\n")

_CANVAS_NOISE_JS = """
  const canvasNoise = makeNoise(CANVAS_SEED);
  const _getImageData = CanvasRenderingContext2D.prototype.getImageData;
  define(CanvasRenderingContext2D.prototype, 'getImageData',
    native(function getImageData(...args) {
      const data = _getImageData.apply(this, args);
      // Perturb only the low bit of a sparse subset: invisible to a human,
      // but stable for this seed — so the canvas hash does not drift between
      // visits to the same site.
      for (let i = 0; i < data.data.length; i += 4) {
        if (canvasNoise() > 0.92) { data.data[i] = data.data[i] ^ 1; }
      }
      return data;
    }, 'getImageData', 1));
""".strip("\n")

_AUDIO_NOISE_JS = """
  const audioNoise = makeNoise(AUDIO_SEED);
  const _getChannelData = AudioBuffer.prototype.getChannelData;
  define(AudioBuffer.prototype, 'getChannelData',
    native(function getChannelData(...args) {
      const data = _getChannelData.apply(this, args);
      for (let i = 0; i < data.length; i += 977) {
        data[i] = data[i] + (audioNoise() - 0.5) * 1e-7;
      }
      return data;
    }, 'getChannelData', 1));
""".strip("\n")


# The helper installer. cdp.py imports this exact constant rather than keeping
# its own copy, so the two modules cannot drift apart. Nothing is attached to
# `window`: every helper stays in the enclosing IIFE closure, because a global
# like `__native` would be one more unique token for a detector to key on.
BOOTSTRAP = """
  const _nativeSrc = Function.prototype.toString;
  const _origSrc = new WeakMap();
  const native = (fn, name, arity) => {
    const wrapped = function (...args) { return fn.apply(this, args); };
    Object.defineProperty(wrapped, 'name',
      { value: name || fn.name || '', configurable: true });
    Object.defineProperty(wrapped, 'length',
      { value: arity === undefined ? (fn.length || 0) : arity, configurable: true });
    _origSrc.set(wrapped, 'function ' + (name || fn.name || '') + '() { [native code] }');
    return wrapped;
  };
  const nativeToString = function toString() {
    const stored = _origSrc.get(this);
    return stored !== undefined ? stored : _nativeSrc.call(this);
  };
  _origSrc.set(nativeToString, 'function toString() { [native code] }');
  Object.defineProperty(Function.prototype, 'toString',
    { value: nativeToString, writable: true, configurable: true });
  const define = (obj, prop, value) => Object.defineProperty(obj, prop, {
    value, writable: true, enumerable: false, configurable: true,
  });
""".strip("\n")


def props_body(spec: BrowserPropertySpec) -> str:
    """The property assignments only — for composition inside a shared IIFE.

    Depends on the ``native()`` and ``define()`` helpers from :data:`BOOTSTRAP`
    being in scope. Use :func:`spoof_script` for a self-contained script.
    """
    return _spoof_body(spec)


def spoof_script(spec: BrowserPropertySpec) -> str:
    """Self-contained property-spoofing init script for ``spec``.

    Byte-identical for identical specs — the temporal-stability requirement
    (FP-Inconsistent's second axis): a device that resamples its canvas hash on
    every visit is as suspicious as one whose headers rotate.
    """
    return "(() => {\n  'use strict';\n" + BOOTSTRAP + "\n\n" + _spoof_body(spec) + "\n})();"


def _spoof_body(spec: BrowserPropertySpec) -> str:
    """The property assignments, shared by both composition modes."""
    return f"""{_NOISE_JS}

  const NAV = Navigator.prototype;
  const SCREEN = Screen.prototype;

  define(NAV, 'platform', {spec.platform!r});
  define(NAV, 'languages', {_js_value(spec.languages)});
  define(NAV, 'language', {_js_value(spec.languages[0]) if spec.languages else "''"});
  define(NAV, 'hardwareConcurrency', {spec.hardware_concurrency});
  define(NAV, 'deviceMemory', {spec.device_memory});
  define(NAV, 'maxTouchPoints', {spec.max_touch_points});
  define(NAV, 'webdriver', false);

  // Intl must agree with the timezone the profile claims, or the mismatch is
  // itself the signal.
  const TZ = {spec.timezone!r};
  const _resolved = Intl.DateTimeFormat.prototype.resolvedOptions;
  define(Intl.DateTimeFormat.prototype, 'resolvedOptions',
    native(function resolvedOptions(...args) {{
      const opts = _resolved.apply(this, args);
      opts.timeZone = TZ;
      return opts;
    }}, 'resolvedOptions', 0));

  define(SCREEN, 'width', {spec.screen[0]});
  define(SCREEN, 'height', {spec.screen[1]});
  define(SCREEN, 'availWidth', {spec.avail[0]});
  define(SCREEN, 'availHeight', {spec.avail[1]});
  define(SCREEN, 'colorDepth', 24);
  define(SCREEN, 'pixelDepth', 24);
  define(window, 'devicePixelRatio', {spec.device_pixel_ratio});

  // Outer dimensions must be non-zero and never smaller than the viewport.
  // Headless windows report zero here, which is a direct tell — and deriving
  // them from the profile's own screen keeps the pair self-consistent.
  define(window, 'outerWidth', {spec.screen[0]});
  define(window, 'outerHeight', {spec.screen[1]});

  define(NAV, 'connection', {{
    effectiveType: '4g', rtt: 50, downlink: 10, saveData: false,
  }});

{_PLUGINS_JS}

  // WebGL must name hardware plausible for the claimed OS; a software renderer
  // is a GPU-less-host tell.
  const _getParameter = WebGLRenderingContext.prototype.getParameter;
  define(WebGLRenderingContext.prototype, 'getParameter',
    native(function getParameter(p) {{
      if (p === 37445) return {spec.webgl.unmasked_vendor!r};
      if (p === 37446) return {spec.webgl.unmasked_renderer!r};
      return _getParameter.apply(this, [p]);
    }}, 'getParameter', 1));

{_CANVAS_NOISE_JS.replace('CANVAS_SEED', str(spec.canvas_noise))}

{_AUDIO_NOISE_JS.replace('AUDIO_SEED', str(spec.audio_noise))}
""".strip("\n")


def probe_script() -> str:
    """JS expression returning the observation surface for :func:`audit_props`.

    Keys match :func:`audit_props`'s expected mapping, so a live
    ``page.evaluate(probe_script())`` and an offline dict exercise the same
    audit code.
    """
    return """(() => (() => { try {
    const canvas = document.createElement('canvas');
    const gl = canvas.getContext('webgl');
    let renderer = null;
    if (gl) {
      const dbg = gl.getExtension('WEBGL_debug_renderer_info');
      renderer = dbg ? String(gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL)) : null;
    }
    return {
      platform: navigator.platform,
      languages: Array.from(navigator.languages || []),
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      screen: [screen.width, screen.height],
      avail: [screen.availWidth, screen.availHeight],
      viewport: [window.innerWidth, window.innerHeight],
      device_pixel_ratio: window.devicePixelRatio,
      hardware_concurrency: navigator.hardwareConcurrency,
      device_memory: navigator.deviceMemory === undefined ? null : navigator.deviceMemory,
      max_touch_points: navigator.maxTouchPoints,
      webgl_renderer: renderer,
      pdf_viewer_enabled: typeof navigator.pdfViewerEnabled === 'boolean'
        ? navigator.pdfViewerEnabled : null,
      plugins_length: navigator.plugins ? navigator.plugins.length : 0,
    };
  } catch (e) { return { error: String(e) }; } })())"""


def audit_props(
    observed: Mapping[str, Any],
    profile: FingerprintProfile,
) -> list[str]:
    """Cross-layer audit of an observed JS surface against ``profile``.

    Only keys present in ``observed`` are judged, so partial probes (or a mock
    surface in tests) still produce a meaningful report. Rules are the ones
    real vendors check: locale/timezone agreement, platform agreement, the
    screen ≥ viewport invariant, and renderer plausibility for the OS.
    """
    issues: list[str] = []

    platform = observed.get("platform")
    expected_platform = _PLATFORM_STRINGS.get(profile.platform_os)
    if platform and expected_platform and platform != expected_platform:
        issues.append(
            f"navigator.platform {platform!r} != UA platform {profile.platform_os!r} "
            f"(expected {expected_platform!r})"
        )

    timezone = observed.get("timezone")
    if timezone and timezone != profile.timezone_id:
        issues.append(f"Intl timeZone {timezone!r} != profile {profile.timezone_id!r}")

    languages = observed.get("languages")
    if languages:
        first = str(languages[0]) if len(languages) else ""
        if first and first.lower() != profile.locale.lower():
            issues.append(f"navigator.languages[0] {first!r} != locale {profile.locale!r}")

    # screen must not be smaller than the viewport — a construction invariant
    # here, and a hard cross-check on any observation.
    screen = observed.get("screen")
    viewport = observed.get("viewport") or list(profile.viewport)
    if screen and viewport and len(screen) >= 2 and len(viewport) >= 2:
        if screen[0] < viewport[0] or screen[1] < viewport[1]:
            issues.append(f"screen {list(screen)} is smaller than viewport {list(viewport)}")

    avail = observed.get("avail")
    if avail and screen and len(avail) >= 2 and len(screen) >= 2:
        if avail[0] > screen[0] or avail[1] > screen[1]:
            issues.append(f"avail {list(avail)} exceeds screen {list(screen)}")

    renderer = observed.get("webgl_renderer")
    if renderer:
        expected = webgl_identity(profile)
        plausible = {w.unmasked_renderer for w in _WEBGL_BY_OS.get(profile.platform_os, ())}
        if renderer != expected.unmasked_renderer and renderer not in plausible:
            issues.append(
                f"WebGL renderer {renderer!r} is not plausible for {profile.platform_os} "
                f"(expected one of {sorted(plausible)})"
            )

    touch = observed.get("max_touch_points")
    if touch is not None:
        mobile = profile.mobile or profile.platform_os in ("Android", "iOS")
        if mobile and not touch:
            issues.append("mobile profile but navigator.maxTouchPoints is 0")
        if not mobile and touch:
            issues.append(f"desktop profile but navigator.maxTouchPoints is {touch}")

    dpr = observed.get("device_pixel_ratio")
    if (
        dpr is not None
        and profile.platform_os == "macOS"
        and dpr == 1
        and profile.viewport[0] > 1600
    ):
        issues.append("macOS with a large viewport but devicePixelRatio 1 is implausible")

    return issues
